# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalfood',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='barrier',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='degreeofserotiny',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='familycommonname',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='imageurl',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plantanimalfood',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plantbarrier',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plantnutrientrequirementsbyregion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plantregion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='serotiny',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='thefamily',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='thefamilycommonname',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': True},
        ),
    ]
